/* Constructor visual ordenable: la UI modifica directamente la visual activa. */
(function () {
  'use strict';
  var state = window.dashboardState; if (!state) return;
  var list = document.getElementById('fieldList'), search = document.getElementById('fieldSearch'), count = document.getElementById('fieldCount'), filterRoot = document.getElementById('dynamicFilters'), type = document.getElementById('builderChartType'), title = document.getElementById('chartTitle'), palette = document.getElementById('chartPalette'), hint = document.getElementById('visualHint'), subtitle = document.getElementById('visualSubtitle'), description = document.getElementById('visualDescription'), dragged;
  var header = { visible: 'headerVisible', showSubtitle: 'headerShowSubtitle', showDescription: 'headerShowDescription', align: 'headerAlign', font: 'headerFont', size: 'headerSize', color: 'headerColor', spacing: 'headerSpacing', bold: 'headerBold', italic: 'headerItalic' }, options = { showLegend: 'showLegend', showTooltip: 'showTooltip', showAnimations: 'showAnimations', decimalPlaces: 'decimalPlaces' };
  var ops = { sum: 'Suma', average: 'Promedio', count: 'Conteo', distinct: 'Conteo distinto', max: 'Máximo', min: 'Mínimo', median: 'Mediana', mode: 'Moda', variance: 'Varianza', stddev: 'Desviación estándar', percentile: 'Percentil' };
  function current() { return state.visuals.find(function (v) { return v.id === state.activeVisualId; }); } function update() { window.updateDashboard(); } function name(item) { return typeof item === 'string' ? item : item && (item.name || item.field); } function key(zone) { return { filters: 'filters', legend: 'legends', category: 'categories', values: 'values' }[zone]; }
  function remove(zone, field) { var v = current(); v[key(zone)] = v[key(zone)].filter(function (item) { return name(item) !== field; }); update(); }
  function add(zone, field, index) { var v = current(), k = key(zone); if (!k || !field || v[k].some(function (item) { return name(item) === field; })) return; var item = zone === 'filters' ? { field: field, value: '' } : zone === 'values' ? { name: field, operation: 'sum', percentile: 50 } : field; if (index == null) v[k].push(item); else v[k].splice(index, 0, item); update(); }
  function fields() { return Object.keys(state.rawData[0] || {}).map(function (field) { var sample = state.rawData.slice(0, 100).map(function (r) { return r[field]; }).filter(function (x) { return x !== '' && x != null; }); return { name: field, numeric: sample.length && sample.filter(function (x) { return Number.isFinite(Number(String(x).replace(',', '.'))); }).length / sample.length > .85 }; }); }
  function chip(zone, item, index) { var field = name(item), node = document.createElement('article'), handle = document.createElement('button'), label = document.createElement('span'), close = document.createElement('button'); node.className = 'field-chip'; node.draggable = true; node.dataset.index = index; handle.type = 'button'; handle.className = 'chip-handle'; handle.textContent = '⠿'; handle.setAttribute('aria-label', 'Reordenar ' + field); label.className = 'chip-name'; label.textContent = field; close.type = 'button'; close.className = 'chip-remove'; close.textContent = '×'; close.setAttribute('aria-label', 'Quitar ' + field); close.onclick = function () { remove(zone, field); }; node.append(handle, label); if (zone === 'values') { var select = document.createElement('select'); select.className = 'chip-operation'; Object.keys(ops).forEach(function (op) { select.add(new Option(ops[op], op, false, item.operation === op)); }); select.setAttribute('aria-label', 'Agregación de ' + field); select.onchange = function () { item.operation = select.value; update(); }; node.appendChild(select); if (item.operation === 'percentile') { var percentile = document.createElement('input'); percentile.type = 'number'; percentile.min = 0; percentile.max = 100; percentile.value = item.percentile || 50; percentile.className = 'chip-percentile'; percentile.onchange = function () { item.percentile = Number(percentile.value) || 50; update(); }; node.appendChild(percentile); } } node.appendChild(close); node.addEventListener('dragstart', function (event) { dragged = { zone: zone, index: index, field: field, internal: true }; event.dataTransfer.setData('text/plain', field); }); return node; }
  function render() { var v = current(); if (!v) return; ['categories', 'legends', 'values', 'filters'].forEach(function (k) { v[k] = Array.isArray(v[k]) ? v[k] : []; }); var all = fields(); if (count) count.textContent = all.length + ' campos'; if (type) type.value = v.type; if (title) title.value = v.title || ''; if (subtitle) subtitle.value = v.subtitle || ''; if (description) description.value = v.description || ''; if (palette) palette.value = v.options.palette || 'blue'; if (hint) hint.textContent = (v.type === 'pie' || v.type === 'doughnut') && (v.values.length > 1 || v.legends.length) ? 'Este gráfico circular sólo muestra una serie. Prueba Barras, Líneas o Tabla; la configuración se conserva.' : (v.values.length ? 'Cambios aplicados al instante.' : 'Arrastra una medida a Valores para comenzar.');
    document.querySelectorAll('.drop-zone').forEach(function (zone) { var k = key(zone.dataset.zone), root = zone.querySelector('.zone-content'); if (!k) return; root.replaceChildren(); v[k].forEach(function (item, index) { root.appendChild(chip(zone.dataset.zone, item, index)); }); });
    Object.keys(header).forEach(function (k) { var control = document.getElementById(header[k]); if (control) control[control.type === 'checkbox' ? 'checked' : 'value'] = v.header[k]; }); Object.keys(options).forEach(function (k) { var control = document.getElementById(options[k]); if (control) control[control.type === 'checkbox' ? 'checked' : 'value'] = v.options[k]; });
    if (filterRoot) { filterRoot.replaceChildren(); v.filters.forEach(function (filter) { var wrap = document.createElement('label'), select = document.createElement('select'); wrap.className = 'dynamic-filter'; wrap.append(document.createTextNode(filter.field)); select.add(new Option('Todos', '')); Array.from(new Set(state.rawData.map(function (row) { return String(row[filter.field] == null ? '' : row[filter.field]); }))).sort().slice(0, 300).forEach(function (value) { select.add(new Option(value || '(vacío)', value, false, value === filter.value)); }); select.onchange = function () { filter.value = select.value; update(); }; wrap.appendChild(select); filterRoot.appendChild(wrap); }); }
    if (list) { var q = (search && search.value || '').toLocaleLowerCase('es'); list.replaceChildren(); all.filter(function (f) { return !q || f.name.toLocaleLowerCase('es').includes(q); }).forEach(function (f) { var button = document.createElement('button'); button.type = 'button'; button.className = 'field-item'; button.draggable = true; button.textContent = (f.numeric ? '∑ ' : 'T ') + f.name; button.onclick = function () { add(f.numeric ? 'values' : 'category', f.name); }; button.addEventListener('dragstart', function (event) { dragged = { field: f.name, internal: false }; event.dataTransfer.setData('text/plain', f.name); }); list.appendChild(button); }); }
  }
  window.renderFieldPanel = render;
  if (search) search.oninput = render; if (type) type.onchange = function () { current().type = type.value; update(); }; if (title) title.oninput = function () { current().title = title.value; update(); }; if (subtitle) subtitle.oninput = function () { current().subtitle = subtitle.value; update(); }; if (description) description.oninput = function () { current().description = description.value; update(); }; if (palette) palette.onchange = function () { current().options.palette = palette.value; update(); };
  Object.keys(header).forEach(function (k) { var c = document.getElementById(header[k]); if (c) c.onchange = function () { current().header[k] = c.type === 'checkbox' ? c.checked : (k === 'size' || k === 'spacing' ? Number(c.value) : c.value); update(); }; }); Object.keys(options).forEach(function (k) { var c = document.getElementById(options[k]); if (c) c.onchange = function () { current().options[k] = c.type === 'checkbox' ? c.checked : Number(c.value); update(); }; });
  document.querySelectorAll('.drop-zone').forEach(function (zone) { zone.addEventListener('dragover', function (e) { if (key(zone.dataset.zone)) { e.preventDefault(); zone.classList.add('drag-over'); } }); zone.addEventListener('dragleave', function () { zone.classList.remove('drag-over'); }); zone.addEventListener('drop', function (e) { e.preventDefault(); zone.classList.remove('drag-over'); var target = zone.dataset.zone, chipTarget = e.target.closest('.field-chip'), at = chipTarget ? Number(chipTarget.dataset.index) : current()[key(target)].length; if (!dragged) return; if (dragged.internal && dragged.zone === target) { var items = current()[key(target)], item = items.splice(dragged.index, 1)[0]; items.splice(at, 0, item); update(); } else { if (dragged.internal) remove(dragged.zone, dragged.field); add(target, dragged.field, at); } dragged = null; }); }); render();
})();
